### ISSUE TITLE
Bug: --ci-build-id arg is ignored in 2.0.0

### ISSUE THREAD

**Issue by runeabrahams1** [currents-dev/currents-nx#19]
https://github.com/currents-dev/currents-nx/blob/f90b3cf2b05e4528b3bcf0ef4ebba920c243f57c/packages/nx/src/executors/currents.impl.ts#L167-L169

This seems to be the issue?

Original issue: We can get parallelization in CI to work after updating to 2.0.0. Seems like BuildId is always set to the current date, so each agent isn't synchronized with cypress-cloud

**Comment by agoldis** [comment]
🤦🏻‍♂️ apologies, that's quite embarrassing. Please let me know if 2.0.1 fixes the problem.

**Comment by yhaiovyi-tripactions** [comment]
Much appreciated
