### ISSUE TITLE
@currents/nx does not support NX version 16.0.0 and above

### ISSUE THREAD

**Issue by osmolovyk** [currents-dev/currents-nx#26]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/currents-dev/currents-nx/issues) and [discussions](https://github.com/currents-dev/currents-nx/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Environment information

<details>

```
NX@16.0.0
```

</details>

### Describe the bug

While executing e2e tests in NX monorepo updated to NX 16.0.0 error message has been shown: 
`Cannot find module '@nrwl/devkit'`

### Expected behavior

e2e test should be executed successfully 

### Command and Setup

nx currents web-e2e --ciBuildId=newBuild

### Full log and debug output

<details>

```
Cannot find module '@nrwl/devkit
```

</details>

**Comment by agoldis** [comment]
[Released](https://github.com/currents-dev/currents-nx/releases/tag/v2.1.0) 
thanks for the contribution @osmolovyk

**Comment by osmolovyk** [comment]
@agoldis 
It seems like the released package is empty :(

**Comment by agoldis** [comment]
huh?

**Comment by agoldis** [comment]
@osmolovyk ok, fixed in 2.1.1
